/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAluno;
import fatec.poo.model.Aluno;
import fatec.poo.model.Pessoa;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class GuiAluno extends javax.swing.JFrame {

    /**
     * Creates new form GuiAluno
     */
    public GuiAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        txtCPF = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtRG = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbEstadocivil = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbEscolaridade = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtDtnasc = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtN = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTelres = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Aluno");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("CPF");

        jLabel2.setText("Nome");

        jLabel3.setText("Sexo");

        jLabel4.setText("Endereço");

        jLabel5.setText("Bairro");

        jLabel6.setText("Cidade");

        jLabel7.setText("RG");

        jLabel8.setText("Email");

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtNome.setEnabled(false);

        txtEndereco.setEnabled(false);

        txtBairro.setEnabled(false);

        txtCidade.setEnabled(false);

        try {
            txtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRG.setEnabled(false);

        txtEmail.setEnabled(false);

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        cmbSexo.setEnabled(false);

        jLabel9.setText("Estado Civil");

        cmbEstadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Divorciado", "Viúvo" }));
        cmbEstadocivil.setEnabled(false);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cmbEstado.setEnabled(false);
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        jLabel10.setText("Estado");

        jLabel11.setText("Escolaridade");

        cmbEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Médio", "Superior", "Pós-graduação", "Mestrado", " " }));
        cmbEscolaridade.setEnabled(false);
        cmbEscolaridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEscolaridadeActionPerformed(evt);
            }
        });

        jLabel12.setText("Data Nascto");

        try {
            txtDtnasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtnasc.setEnabled(false);

        jLabel13.setText("Nº");

        txtN.setEnabled(false);

        jLabel14.setText("CEP");

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setEnabled(false);
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });

        jLabel15.setText("Tel. Res");

        jLabel16.setText("Celular");

        try {
            txtTelres.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelres.setEnabled(false);

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setEnabled(false);

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar)
                        .addGap(27, 27, 27)
                        .addComponent(btnExcluir)
                        .addGap(19, 19, 19)
                        .addComponent(btnSair)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTelres)
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbEstadocivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDtnasc))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBairro, txtEndereco});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEmail, txtNome});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbSexo, txtCPF, txtRG});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(cmbEstadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtDtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cmbEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultar)
                            .addComponent(btnInserir)
                            .addComponent(btnAlterar)
                            .addComponent(btnExcluir)
                            .addComponent(btnSair)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBairro, txtEndereco});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEmail, txtNome});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbSexo, txtCPF, txtRG});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void cmbEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEscolaridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEscolaridadeActionPerformed

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        aluno = null;
        aluno = daoAluno.consultar(txtCPF.getText());

        if (aluno == null) {
            txtCPF.setEnabled(false);
            txtNome.setEnabled(true);
            txtDtnasc.setEnabled(true);
            cmbSexo.setEnabled(true);
            cmbEstadocivil.setEnabled(true);
            txtEndereco.setEnabled(true);
            txtN.setEnabled(true);
            txtBairro.setEnabled(true);
            txtCEP.setEnabled(true);
            txtCidade.setEnabled(true);
            cmbEstado.setEnabled(true);
            txtTelres.setEnabled(true);
            txtRG.setEnabled(true);
            txtCelular.setEnabled(true);
            cmbEscolaridade.setEnabled(true);
            txtEmail.setEnabled(true);
            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(true);
            txtNome.requestFocus();
        } else {
            txtCPF.setEnabled(false);
            txtNome.setEnabled(true);
            txtDtnasc.setEnabled(true);
            cmbSexo.setEnabled(true);
            cmbEstadocivil.setEnabled(true);
            txtEndereco.setEnabled(true);
            txtN.setEnabled(true);
            txtBairro.setEnabled(true);
            txtCEP.setEnabled(true);
            txtCidade.setEnabled(true);
            cmbEstado.setEnabled(true);
            txtTelres.setEnabled(true);
            txtRG.setEnabled(true);
            txtCelular.setEnabled(true);
            cmbEscolaridade.setEnabled(true);
            txtEmail.setEnabled(true);
            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(true);

            txtNome.setText(aluno.getNome());
            txtDtnasc.setText(aluno.getDataNasc());
            txtEndereco.setText(aluno.getEndereco());
            txtN.setText(Integer.toString(aluno.getNumero()));
            txtBairro.setText(aluno.getBairro());
            txtCEP.setText(aluno.getCep());
            txtCidade.setText(aluno.getCidade());
            txtTelres.setText(aluno.getTelefone());
            txtRG.setText(aluno.getRg());
            txtCelular.setText(aluno.getCelular());

            txtEmail.setText(aluno.getEmail());

            if ("M".equals(aluno.getSexo())) {
                cmbSexo.setSelectedIndex(0);
            } else {
                cmbSexo.setSelectedIndex(1);
            }

            if ("Solteiro".equals(aluno.getEstadoCivil())) {
                cmbEstadocivil.setSelectedIndex(0);
            } else if ("Casado".equals(aluno.getEstadoCivil())) {
                cmbEstadocivil.setSelectedIndex(1);
            } else if ("Divorciado".equals(aluno.getEstadoCivil())) {
                cmbEstadocivil.setSelectedIndex(2);
            } else {
                cmbEstadocivil.setSelectedIndex(3);
            }

            if ("Médio".equals(aluno.getEscolaridade())) {
                cmbEscolaridade.setSelectedIndex(0);
            } else if ("Superior".equals(aluno.getEscolaridade())) {
                cmbEscolaridade.setSelectedIndex(1);
            } else if ("Pós-graduação".equals(aluno.getEscolaridade())) {
                cmbEscolaridade.setSelectedItem(2);
            } else {
                cmbEscolaridade.setSelectedItem(3);
            }

            String estado = aluno.getEstado();
            switch (estado) {
                case "AC":
                    cmbEstado.setSelectedIndex(0);
                case "AL":
                    cmbEstado.setSelectedIndex(1);
                case "AP":
                    cmbEstado.setSelectedIndex(2);
                case "AM":
                    cmbEstado.setSelectedIndex(3);
                case "BA":
                    cmbEstado.setSelectedIndex(4);
                case "CE":
                    cmbEstado.setSelectedIndex(5);
                case "DF":
                    cmbEstado.setSelectedIndex(6);
                case "ES":
                    cmbEstado.setSelectedIndex(7);
                case "GO":
                    cmbEstado.setSelectedIndex(8);
                case "MA":
                    cmbEstado.setSelectedIndex(9);
                case "MT":
                    cmbEstado.setSelectedIndex(10);
                case "MS":
                    cmbEstado.setSelectedIndex(11);
                case "MG":
                    cmbEstado.setSelectedIndex(12);
                case "PA":
                    cmbEstado.setSelectedIndex(13);
                case "PB":
                    cmbEstado.setSelectedIndex(14);
                case "PR":
                    cmbEstado.setSelectedIndex(15);
                case "PE":
                    cmbEstado.setSelectedIndex(16);
                case "PI":
                    cmbEstado.setSelectedIndex(17);
                case "RJ":
                    cmbEstado.setSelectedIndex(18);
                case "RN":
                    cmbEstado.setSelectedIndex(19);
                case "RS":
                    cmbEstado.setSelectedIndex(20);
                case "RO":
                    cmbEstado.setSelectedIndex(21);
                case "RR":
                    cmbEstado.setSelectedIndex(22);
                case "SC":
                    cmbEstado.setSelectedIndex(23);
                case "SP":
                    cmbEstado.setSelectedIndex(24);
                case "SE":
                    cmbEstado.setSelectedIndex(25);
                default:
                    cmbEstado.setSelectedIndex(26);
            }

            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnInserir.setEnabled(false);
            btnConsultar.setEnabled(false);
            txtNome.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        if (Pessoa.validarCPF(txtCPF.getText())) {
            String sexo = (String) cmbSexo.getSelectedItem();
            String estadocivil = (String) cmbEstadocivil.getSelectedItem();
            String escolaridade = (String) cmbEscolaridade.getSelectedItem();
            String estado = (String) cmbEstado.getSelectedItem();
            aluno = new Aluno(txtCPF.getText(), txtNome.getText());
            aluno.setEscolaridade(escolaridade);
            aluno.setNumero(Integer.parseInt(txtN.getText()));
            aluno.setBairro(txtBairro.getText());
            aluno.setCidade(txtCidade.getText());
            aluno.setDataNasc(txtDtnasc.getText());
            aluno.setSexo(sexo);
            aluno.setEmail(txtEmail.getText());
            aluno.setEstado(estado);
            aluno.setTelefone(txtTelres.getText());
            aluno.setRg(txtRG.getText());
            aluno.setCelular(txtCelular.getText());
            aluno.setEndereco(txtEndereco.getText());
            aluno.setCep(txtCEP.getText());
            aluno.setEstadoCivil(estadocivil);
            daoAluno.inserir(aluno);

            txtCPF.setEnabled(true);
            txtNome.setEnabled(false);
            txtDtnasc.setEnabled(false);
            cmbSexo.setEnabled(false);
            cmbEstadocivil.setEnabled(false);
            txtEndereco.setEnabled(false);
            txtN.setEnabled(false);
            txtBairro.setEnabled(false);
            txtCEP.setEnabled(false);
            txtCidade.setEnabled(false);
            cmbEstado.setEnabled(false);
            txtTelres.setEnabled(false);
            txtRG.setEnabled(false);
            txtCelular.setEnabled(false);
            txtEmail.setEnabled(false);
            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);

            txtCPF.setText("");
            txtNome.setText("");
            txtDtnasc.setText("");
            cmbSexo.setToolTipText("M");
            cmbEstadocivil.setToolTipText("Solteiro");
            txtEndereco.setText("");
            txtN.setText("");
            txtBairro.setText("");
            txtCEP.setText("");
            txtCidade.setText("");
            cmbEstado.setToolTipText("SP");
            cmbEscolaridade.setToolTipText("Médio");
            txtTelres.setText("");
            txtRG.setText("");
            txtCelular.setText("");
            txtEmail.setText("");
            txtCPF.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null, "CPF Inválido");
            txtCPF.setEnabled(true);
        }


    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirmar Alteração?") == 0) {
            String sexo = (String) cmbSexo.getSelectedItem();
            String estadocivil = (String) cmbEstadocivil.getSelectedItem();
            String escolaridade = (String) cmbEscolaridade.getSelectedItem();
            String estado = (String) cmbEstado.getSelectedItem();
            aluno = new Aluno(txtCPF.getText(), txtNome.getText());
            aluno.setEscolaridade(escolaridade);
            aluno.setNumero(Integer.parseInt(txtN.getText()));
            aluno.setBairro(txtBairro.getText());
            aluno.setCidade(txtCidade.getText());
            aluno.setDataNasc(txtDtnasc.getText());
            aluno.setSexo(sexo);
            aluno.setEmail(txtEmail.getText());
            aluno.setEstado(estado);
            aluno.setTelefone(txtTelres.getText());
            aluno.setRg(txtRG.getText());
            aluno.setCelular(txtCelular.getText());
            aluno.setEndereco(txtEndereco.getText());
            aluno.setCep(txtCEP.getText());
            aluno.setEstadoCivil(estadocivil);
            daoAluno.alterar(aluno);

            txtCPF.setEnabled(true);
            txtNome.setEnabled(false);
            txtDtnasc.setEnabled(false);
            cmbSexo.setEnabled(false);
            cmbEstadocivil.setEnabled(false);
            txtEndereco.setEnabled(false);
            txtN.setEnabled(false);
            txtBairro.setEnabled(false);
            txtCEP.setEnabled(false);
            txtCidade.setEnabled(false);
            cmbEstado.setEnabled(false);
            txtTelres.setEnabled(false);
            txtRG.setEnabled(false);
            txtCelular.setEnabled(false);
            txtEmail.setEnabled(false);
            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);

            txtCPF.setText("");
            txtNome.setText("");
            txtDtnasc.setText("");
            cmbSexo.setToolTipText("M");
            cmbEstadocivil.setToolTipText("Solteiro");
            txtEndereco.setText("");
            txtN.setText("");
            txtBairro.setText("");
            txtCEP.setText("");
            txtCidade.setText("");
            cmbEstado.setToolTipText("SP");
            cmbEscolaridade.setToolTipText("Médio");
            txtTelres.setText("");
            txtRG.setText("");
            txtCelular.setText("");
            txtEmail.setText("");
            txtCPF.requestFocus();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirmar Exclusão?") == 0) {

            daoAluno.excluir(txtCPF.getText());

            txtCPF.setEnabled(true);
            txtNome.setEnabled(false);
            txtDtnasc.setEnabled(false);
            cmbSexo.setEnabled(false);
            cmbEstadocivil.setEnabled(false);
            txtEndereco.setEnabled(false);
            txtN.setEnabled(false);
            txtBairro.setEnabled(false);
            txtCEP.setEnabled(false);
            txtCidade.setEnabled(false);
            cmbEstado.setEnabled(false);
            txtTelres.setEnabled(false);
            txtRG.setEnabled(false);
            txtCelular.setEnabled(false);
            txtEmail.setEnabled(false);
            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);

            txtCPF.setText("");
            txtNome.setText("");
            txtDtnasc.setText("");
            cmbSexo.setToolTipText("M");
            cmbEstadocivil.setToolTipText("Solteiro");
            txtEndereco.setText("");
            txtN.setText("");
            txtBairro.setText("");
            txtCEP.setText("");
            txtCidade.setText("");
            cmbEstado.setToolTipText("SP");
            cmbEscolaridade.setToolTipText("Médio");
            txtTelres.setText("");
            txtRG.setText("");
            txtCelular.setText("");
            txtEmail.setText("");
            txtCPF.requestFocus();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("", "");
        conexao.setConnectionString("jdbc:ucanaccess://F:\\Dowloands\\prjPOOEduardoGabriel\\src\\fatec\\poo\\basededados\\bdPOO.accdb\\");
        conexao.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
        daoAluno = new DaoAluno(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAluno().setVisible(true);
            }
        });
    }

    Aluno aluno = null;
    DaoAluno daoAluno = null;
    Conexao conexao = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cmbEscolaridade;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbEstadocivil;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtDtnasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRG;
    private javax.swing.JFormattedTextField txtTelres;
    // End of variables declaration//GEN-END:variables
}
