/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAPrazo;
import fatec.poo.control.DaoAVista;
import fatec.poo.control.DaoAluno;
import fatec.poo.control.DaoCurso;
import fatec.poo.control.DaoMatricula;
import fatec.poo.control.DaoTurma;
import fatec.poo.model.APrazo;
import fatec.poo.model.AVista;
import fatec.poo.model.Aluno;
import fatec.poo.model.Curso;
import fatec.poo.model.Matricula;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Turma;
import java.util.ArrayList;

/**
 *
 * @author aluno
 */
public class GuiEfetuarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form GuiEfetuarMatricula
     */
    public GuiEfetuarMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdnAvista = new javax.swing.JRadioButton();
        rdnParcelado = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JTextField();
        txtQtdMensal = new javax.swing.JTextField();
        txtNcheque = new javax.swing.JTextField();
        txtJuros = new javax.swing.JTextField();
        txtDataPagto = new javax.swing.JFormattedTextField();
        txtData1Vencto = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        cmbCurso = new javax.swing.JComboBox<>();
        cmbTurma = new javax.swing.JComboBox<>();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtDataMatricula = new javax.swing.JFormattedTextField();
        txtCPFAluno = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Efetuar Matricula");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Data da Matrícula");
        jLabel1.setToolTipText("");

        jLabel2.setText("Curso");

        jLabel3.setText("Turma");

        jLabel4.setText("CPF Aluno");

        jLabel5.setText("Valor");

        jLabel6.setText("Nome");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));
        jPanel1.setToolTipText("");
        jPanel1.setEnabled(false);
        jPanel1.setName(""); // NOI18N

        buttonGroup1.add(rdnAvista);
        rdnAvista.setText("Á vista");
        rdnAvista.setEnabled(false);
        rdnAvista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnAvistaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdnParcelado);
        rdnParcelado.setText("Parcelado");
        rdnParcelado.setEnabled(false);
        rdnParcelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnParceladoActionPerformed(evt);
            }
        });

        jLabel7.setText("Agência");

        jLabel8.setText("Qtde. Mensalidades");

        jLabel9.setText("No. Cheque");

        jLabel10.setText("Tx. Juros(%)");

        jLabel11.setText("Data Pagto.");

        jLabel12.setText("Data 1o. Vencto.");

        txtAgencia.setEnabled(false);

        txtQtdMensal.setEnabled(false);

        txtNcheque.setText("  ");
        txtNcheque.setEnabled(false);
        txtNcheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNchequeActionPerformed(evt);
            }
        });

        txtJuros.setEnabled(false);

        try {
            txtDataPagto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataPagto.setEnabled(false);

        try {
            txtData1Vencto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData1Vencto.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdnParcelado)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(4, 4, 4)
                        .addComponent(txtData1Vencto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdnAvista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(9, 9, 9)
                        .addComponent(txtNcheque, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdnAvista)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNcheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdnParcelado)
                    .addComponent(jLabel8)
                    .addComponent(txtQtdMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtData1Vencto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        txtValor.setEnabled(false);

        txtNome.setEnabled(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        cmbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursoActionPerformed(evt);
            }
        });

        cmbTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTurmaActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        txtDataMatricula.setEditable(false);
        try {
            txtDataMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCPFAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPFAlunoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCPFAluno))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInserir)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void rdnAvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnAvistaActionPerformed
        if(rdnAvista.isSelected()){
            txtAgencia.setEnabled(true);
            txtNcheque.setEnabled(true);
            txtDataPagto.setEnabled(true);
            txtQtdMensal.setEnabled(false);
            txtJuros.setEnabled(false);
            txtData1Vencto.setEnabled(false);
        }
    }//GEN-LAST:event_rdnAvistaActionPerformed

    private void txtNchequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNchequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNchequeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("", "");
        conexao.setConnectionString("jdbc:ucanaccess://F:\\Dowloands\\prjPOOEduardoGabriel\\src\\fatec\\poo\\basededados\\bdPOO.accdb\\");
        conexao.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
        
        daoTurma = new DaoTurma(conexao.conectar());
        daoCurso = new DaoCurso(conexao.conectar());
        daoAluno = new DaoAluno(conexao.conectar());
        daoMatricula = new DaoMatricula(conexao.conectar());
        daoAvista = new DaoAVista(conexao.conectar());
        daoPrazo = new DaoAPrazo(conexao.conectar());
        cursos = daoCurso.listarSiglas();
        
        for (int i = 0; i < cursos.size(); i++) {
            turmas = daoTurma.listarTurmas(cursos.get(i).getSigla());
            for(int y = 0; y < turmas.size(); y++){
                cursos.get(i).addTurma(turmas.get(y));
            }
            cmbCurso.addItem(cursos.get(i).getSigla());
        }
    }//GEN-LAST:event_formWindowOpened

    private void cmbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursoActionPerformed
        cmbTurma.removeAllItems();
        for(int i = 0; i < cursos.size(); i++){
            if(cmbCurso.getSelectedItem().toString().equals(cursos.get(i).getSigla())){
                for(int y = 0; y < cursos.get(i).getTurmas().size(); y++){
                    cmbTurma.addItem(cursos.get(i).getTurmas().get(y).getSiglaTurma());
                }
            }
        }
        
        for(int i = 0; i < cursos.size(); i++){
            if(cmbCurso.getSelectedItem().toString().equals(cursos.get(i).getSigla())){
               txtValor.setText(Double.toString(cursos.get(i).getValor()));
            }
        }
    }//GEN-LAST:event_cmbCursoActionPerformed

    private void cmbTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTurmaActionPerformed
        txtCPFAluno.setEnabled(true);
        rdnAvista.setEnabled(true);
        rdnParcelado.setEnabled(true);
    }//GEN-LAST:event_cmbTurmaActionPerformed

    private void txtCPFAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFAlunoKeyReleased
        if(Pessoa.validarCPF(txtCPFAluno.getText())){
            aluno = daoAluno.consultar(txtCPFAluno.getText());
            txtNome.setText(aluno.getNome());
        }else{
            txtNome.setText("CPF INVALIDO");
        }
    }//GEN-LAST:event_txtCPFAlunoKeyReleased

    private void rdnParceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnParceladoActionPerformed
        if(rdnParcelado.isSelected()){
            txtAgencia.setEnabled(false);
            txtNcheque.setEnabled(false);
            txtDataPagto.setEnabled(false);
            txtQtdMensal.setEnabled(true);
            txtJuros.setEnabled(true);
            txtData1Vencto.setEnabled(true);
        }
    }//GEN-LAST:event_rdnParceladoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        matricula = daoMatricula.verificarMatricula(cmbTurma.getSelectedItem().toString(), txtCPFAluno.getText());
        if(matricula != null){
            btnConsultar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnConsultar.setEnabled(false);
            
            txtAgencia.setText(matricula.getData());
            if(matricula.getaPrazo() != null){
                txtQtdMensal.setText(Integer.toString(matricula.getaPrazo().getQtdeMensalidade()));
                txtJuros.setText(Double.toString(matricula.getaPrazo().getTaxaJuros()));
                txtData1Vencto.setText(matricula.getaPrazo().getDtVencimento());
            }else{
                txtAgencia.setText(Integer.toString(matricula.getaVista().getAgencia()));
                txtNcheque.setText(Integer.toString(matricula.getaVista().getnCheque()));
                txtDataPagto.setText(matricula.getaVista().getPreData());
            }
        }else{
            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        matricula = daoMatricula.verificarMatricula(cmbTurma.getSelectedItem().toString(), txtCPFAluno.getText());
        daoMatricula.excluir(matricula.getCod());
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        matricula = daoMatricula.verificarMatricula(cmbTurma.getSelectedItem().toString(), txtCPFAluno.getText());
        if(rdnAvista.isSelected()){
            vista = new AVista(matricula.getaVista().getCode());
            vista.setAgencia(Integer.parseInt(txtAgencia.getText()));
            vista.setnCheque(Integer.parseInt(txtNcheque.getText()));
            vista.setPreData(txtDataPagto.getText());
            vista.setValor(Double.parseDouble(txtValor.getText()));
            daoAvista.alterar(vista);
        }else{
            prazo = new APrazo(matricula.getaPrazo().getCod());
            prazo.setDtVencimento(txtData1Vencto.getText());
            prazo.setQtdeMensalidade(Integer.parseInt(txtQtdMensal.getText()));
            prazo.setTaxaJuros(Double.parseDouble(txtJuros.getText()));
            prazo.setValor(Double.parseDouble(txtValor.getText()));
            daoPrazo.alterar(prazo);
        }
        matricula = new Matricula(txtDataMatricula.getText());
        turma = new Turma(cmbTurma.getSelectedItem().toString(), "");
        aluno = new Aluno(txtCPFAluno.getText(), "");

        daoMatricula.alterar(matricula);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        matricula = new Matricula(txtDataMatricula.getText());
        turma = new Turma(cmbTurma.getSelectedItem().toString(), "");
        aluno = new Aluno(txtCPFAluno.getText(), "");
        
        if(rdnAvista.isSelected()){
            vista = new AVista(0);
            vista.setAgencia(Integer.parseInt(txtAgencia.getText()));
            vista.setnCheque(Integer.parseInt(txtNcheque.getText()));
            vista.setPreData(txtDataPagto.getText());
            vista.setValor(Double.parseDouble(txtValor.getText()));
            int cod = daoAvista.inserir(vista);
            vista.setCode(cod);
            matricula.setaVista(vista);
        }else{
            prazo = new APrazo(0);
            prazo.setDtVencimento(txtData1Vencto.getText());
            prazo.setQtdeMensalidade(Integer.parseInt(txtQtdMensal.getText()));
            prazo.setTaxaJuros(Double.parseDouble(txtJuros.getText()));
            int cod = daoPrazo.inserir(prazo);
            prazo.setCod(cod);
            matricula.setaPrazo(prazo);
        }
        
        daoMatricula.inserir(matricula);
        
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiEfetuarMatricula().setVisible(true);
            }
        });
    }
    
    private Conexao conexao = null;
    private DaoTurma daoTurma = null;
    private DaoCurso daoCurso = null;
    private DaoAluno daoAluno = null;
    private DaoAVista daoAvista = null;
    private DaoMatricula daoMatricula = null;
    private DaoAPrazo daoPrazo = null;
    ArrayList<Curso> cursos = null;
    ArrayList<Turma> turmas = null;
    private Turma turma = null;
    private APrazo prazo = null;
    private AVista vista = null;
    private Matricula matricula = null;
    private Curso curso = null;
    private Aluno aluno = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JComboBox<String> cmbTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdnAvista;
    private javax.swing.JRadioButton rdnParcelado;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JFormattedTextField txtCPFAluno;
    private javax.swing.JFormattedTextField txtData1Vencto;
    private javax.swing.JFormattedTextField txtDataMatricula;
    private javax.swing.JFormattedTextField txtDataPagto;
    private javax.swing.JTextField txtJuros;
    private javax.swing.JTextField txtNcheque;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQtdMensal;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
