/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoCurso;
import fatec.poo.control.DaoInstrutor;
import fatec.poo.model.Instrutor;
import fatec.poo.model.Pessoa;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class GuiInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form GuiInstrutor
     */
    public GuiInstrutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtRG = new javax.swing.JFormattedTextField();
        txtFormacao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbxEstadoCivil = new javax.swing.JComboBox<>();
        txtData = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtCPF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Instrutor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("CPF");

        txtNome.setEnabled(false);

        jLabel2.setText("Nome");

        jLabel3.setText("Sexo");

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        cbxSexo.setEnabled(false);

        jLabel4.setText("Endereço");

        txtEndereco.setEnabled(false);

        jLabel5.setText("Bairro");

        txtBairro.setEnabled(false);

        jLabel6.setText("Cidade");

        txtCidade.setEnabled(false);

        jLabel7.setText("Estado");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbxEstado.setEnabled(false);

        jLabel8.setText("RG");

        try {
            txtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRG.setEnabled(false);

        txtFormacao.setEnabled(false);

        jLabel9.setText("Formação");

        jLabel10.setText("Email");

        txtEmail.setEnabled(false);

        jLabel11.setText("Data Nascto");

        jLabel12.setText("Estado Civil");

        cbxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Divorciado", "Viúvo" }));
        cbxEstadoCivil.setEnabled(false);

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setEnabled(false);

        jLabel13.setText("Nº");

        txtNumero.setEnabled(false);

        jLabel14.setText("CEP");

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setEnabled(false);

        jLabel15.setText("Tel. Res");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setEnabled(false);

        jLabel16.setText("Celular");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setEnabled(false);

        jLabel17.setText("Área de atuação");

        txtArea.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(125, 125, 125)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel12)
                                                            .addComponent(jLabel11)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel13)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(107, 107, 107)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtCEP))))))))
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addComponent(txtBairro))
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxEstadoCivil, txtData});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCEP, txtCelular, txtTelefone});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxSexo, txtCPF});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(29, 29, 29))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxSexo, txtCPF});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        instrutor = null;
        instrutor = daoInstrutor.consultar(txtCPF.getText());

        if (instrutor == null) {
            txtCPF.setEnabled(false);
            txtNome.setEnabled(true);
            txtData.setEnabled(true);
            cbxSexo.setEnabled(true);
            cbxEstadoCivil.setEnabled(true);
            txtEndereco.setEnabled(true);
            txtNumero.setEnabled(true);
            txtBairro.setEnabled(true);
            txtCEP.setEnabled(true);
            txtCidade.setEnabled(true);
            cbxEstado.setEnabled(true);
            txtTelefone.setEnabled(true);
            txtRG.setEnabled(true);
            txtCelular.setEnabled(true);
            txtFormacao.setEnabled(true);
            txtArea.setEnabled(true);
            txtEmail.setEnabled(true);
            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(true);
            txtNome.requestFocus();
        } else {
            txtCPF.setEnabled(false);
            txtNome.setEnabled(true);
            txtData.setEnabled(true);
            cbxSexo.setEnabled(true);
            cbxEstadoCivil.setEnabled(true);
            txtEndereco.setEnabled(true);
            txtNumero.setEnabled(true);
            txtBairro.setEnabled(true);
            txtCEP.setEnabled(true);
            txtCidade.setEnabled(true);
            cbxEstado.setEnabled(true);
            txtTelefone.setEnabled(true);
            txtRG.setEnabled(true);
            txtCelular.setEnabled(true);
            txtEmail.setEnabled(true);
            btnConsultar.setEnabled(false);
            txtArea.setEnabled(true);
            txtFormacao.setEnabled(true);

            txtNome.setText(instrutor.getNome());
            txtData.setText(instrutor.getDataNasc());
            txtEndereco.setText(instrutor.getEndereco());
            txtNumero.setText(Integer.toString(instrutor.getNumero()));
            txtBairro.setText(instrutor.getBairro());
            txtCEP.setText(instrutor.getCep());
            txtCidade.setText(instrutor.getCidade());
            txtTelefone.setText(instrutor.getTelefone());
            txtRG.setText(instrutor.getRg());
            txtCelular.setText(instrutor.getCelular());
            txtFormacao.setText(instrutor.getFormacao());
            txtArea.setText(instrutor.getAreaAtuacao());
            txtEmail.setText(instrutor.getEmail());

            if ("M".equals(instrutor.getSexo())) {
                cbxSexo.setSelectedIndex(0);
            } else {
                cbxSexo.setSelectedIndex(1);
            }

            if ("Solteiro".equals(instrutor.getEstadoCivil())) {
                cbxEstadoCivil.setSelectedIndex(0);
            } else if ("Casado".equals(instrutor.getEstadoCivil())) {
                cbxEstadoCivil.setSelectedIndex(1);
            } else if ("Divorciado".equals(instrutor.getEstadoCivil())) {
                cbxEstadoCivil.setSelectedIndex(2);
            } else {
                cbxEstadoCivil.setSelectedIndex(3);
            }

            String estado = instrutor.getEstado();
            switch (estado) {
                case "AC":
                    cbxEstado.setSelectedIndex(0);
                case "AL":
                    cbxEstado.setSelectedIndex(1);
                case "AP":
                    cbxEstado.setSelectedIndex(2);
                case "AM":
                    cbxEstado.setSelectedIndex(3);
                case "BA":
                    cbxEstado.setSelectedIndex(4);
                case "CE":
                    cbxEstado.setSelectedIndex(5);
                case "DF":
                    cbxEstado.setSelectedIndex(6);
                case "ES":
                    cbxEstado.setSelectedIndex(7);
                case "GO":
                    cbxEstado.setSelectedIndex(8);
                case "MA":
                    cbxEstado.setSelectedIndex(9);
                case "MT":
                    cbxEstado.setSelectedIndex(10);
                case "MS":
                    cbxEstado.setSelectedIndex(11);
                case "MG":
                    cbxEstado.setSelectedIndex(12);
                case "PA":
                    cbxEstado.setSelectedIndex(13);
                case "PB":
                    cbxEstado.setSelectedIndex(14);
                case "PR":
                    cbxEstado.setSelectedIndex(15);
                case "PE":
                    cbxEstado.setSelectedIndex(16);
                case "PI":
                    cbxEstado.setSelectedIndex(17);
                case "RJ":
                    cbxEstado.setSelectedIndex(18);
                case "RN":
                    cbxEstado.setSelectedIndex(19);
                case "RS":
                    cbxEstado.setSelectedIndex(20);
                case "RO":
                    cbxEstado.setSelectedIndex(21);
                case "RR":
                    cbxEstado.setSelectedIndex(22);
                case "SC":
                    cbxEstado.setSelectedIndex(23);
                case "SP":
                    cbxEstado.setSelectedIndex(24);
                case "SE":
                    cbxEstado.setSelectedIndex(25);
                default:
                    cbxEstado.setSelectedIndex(26);
            }

            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnInserir.setEnabled(false);
            btnConsultar.setEnabled(false);
            txtNome.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("", "");
        conexao.setConnectionString("jdbc:ucanaccess://F:\\Área de Trabalho\\POO\\prjPOOEduardoGabriel\\src\\fatec\\poo\\basededados\\bdPOO.accdb\\");
        conexao.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
        daoInstrutor = new DaoInstrutor(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed

        if (Pessoa.validarCPF(txtCPF.getText())) {
            String sexo = (String) cbxSexo.getSelectedItem();
            String estadocivil = (String) cbxEstadoCivil.getSelectedItem();
            String estado = (String) cbxEstado.getSelectedItem();
            instrutor = new Instrutor(txtCPF.getText(), txtNome.getText());
            instrutor.setAreaAtuacao(txtArea.getText());
            instrutor.setNumero(Integer.parseInt(txtNumero.getText()));
            instrutor.setBairro(txtBairro.getText());
            instrutor.setCidade(txtCidade.getText());
            instrutor.setDataNasc(txtData.getText());
            instrutor.setSexo(sexo);
            instrutor.setEmail(txtEmail.getText());
            instrutor.setEstado(estado);
            instrutor.setFormacao(txtFormacao.getText());
            instrutor.setTelefone(txtTelefone.getText());
            instrutor.setRg(txtRG.getText());
            instrutor.setCelular(txtCelular.getText());
            instrutor.setEndereco(txtEndereco.getText());
            instrutor.setCep(txtCEP.getText());
            instrutor.setEstadoCivil(estadocivil);
            daoInstrutor.inserir(instrutor);

            txtCPF.setEnabled(true);
            txtNome.setEnabled(false);
            txtData.setEnabled(false);
            cbxSexo.setEnabled(false);
            cbxEstadoCivil.setEnabled(false);
            txtEndereco.setEnabled(false);
            txtNumero.setEnabled(false);
            txtBairro.setEnabled(false);
            txtCEP.setEnabled(false);
            txtCidade.setEnabled(false);
            cbxEstado.setEnabled(false);
            txtTelefone.setEnabled(false);
            txtRG.setEnabled(false);
            txtCelular.setEnabled(false);
            txtEmail.setEnabled(false);
            txtFormacao.setEnabled(false);
            txtArea.setEnabled(false);
            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);

            txtCPF.setText("");
            txtNome.setText("");
            txtData.setText("");
            cbxSexo.setToolTipText("M");
            cbxEstadoCivil.setToolTipText("Solteiro");
            txtEndereco.setText("");
            txtNumero.setText("");
            txtBairro.setText("");
            txtCEP.setText("");
            txtCidade.setText("");
            cbxEstado.setToolTipText("SP");
            txtTelefone.setText("");
            txtRG.setText("");
            txtCelular.setText("");
            txtEmail.setText("");
            txtFormacao.setText("");
            txtArea.setText("");
            txtCPF.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null, "CPF Inválido");
            txtCPF.setEnabled(true);
        }


    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirmar Exclusão?") == 0) {

            String sexo = (String) cbxSexo.getSelectedItem();
            String estadocivil = (String) cbxEstadoCivil.getSelectedItem();
            String estado = (String) cbxEstado.getSelectedItem();
            instrutor = new Instrutor(txtCPF.getText(), txtNome.getText());
            instrutor.setAreaAtuacao(txtArea.getText());
            instrutor.setNumero(Integer.parseInt(txtNumero.getText()));
            instrutor.setBairro(txtBairro.getText());
            instrutor.setCidade(txtCidade.getText());
            instrutor.setDataNasc(txtData.getText());
            instrutor.setSexo(sexo);
            instrutor.setEmail(txtEmail.getText());
            instrutor.setEstado(estado);
            instrutor.setFormacao(txtFormacao.getText());
            instrutor.setTelefone(txtTelefone.getText());
            instrutor.setRg(txtRG.getText());
            instrutor.setCelular(txtCelular.getText());
            instrutor.setEndereco(txtEndereco.getText());
            instrutor.setCep(txtCEP.getText());
            instrutor.setEstadoCivil(estadocivil);
            daoInstrutor.inserir(instrutor);

            txtCPF.setEnabled(true);
            txtNome.setEnabled(false);
            txtData.setEnabled(false);
            cbxSexo.setEnabled(false);
            cbxEstadoCivil.setEnabled(false);
            txtEndereco.setEnabled(false);
            txtNumero.setEnabled(false);
            txtBairro.setEnabled(false);
            txtCEP.setEnabled(false);
            txtCidade.setEnabled(false);
            cbxEstado.setEnabled(false);
            txtTelefone.setEnabled(false);
            txtRG.setEnabled(false);
            txtCelular.setEnabled(false);
            txtEmail.setEnabled(false);
            txtFormacao.setEnabled(false);
            txtArea.setEnabled(false);
            btnConsultar.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnInserir.setEnabled(false);

            txtCPF.setText("");
            txtNome.setText("");
            txtData.setText("");
            cbxSexo.setToolTipText("M");
            cbxEstadoCivil.setToolTipText("Solteiro");
            txtEndereco.setText("");
            txtNumero.setText("");
            txtBairro.setText("");
            txtCEP.setText("");
            txtCidade.setText("");
            cbxEstado.setToolTipText("SP");
            txtCelular.setText("");
            txtRG.setText("");
            txtTelefone.setText("");
            txtEmail.setText("");
            txtFormacao.setText("");
            txtArea.setText("");
            txtCPF.requestFocus();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {
            daoInstrutor.excluir(txtCPF.getText());

            txtCPF.setEnabled(true);
            txtNome.setEnabled(false);
            txtData.setEnabled(false);
            cbxSexo.setEnabled(false);
            cbxEstadoCivil.setEnabled(false);
            txtEndereco.setEnabled(false);
            txtNumero.setEnabled(false);
            txtBairro.setEnabled(false);
            txtCEP.setEnabled(false);
            txtCidade.setEnabled(false);
            cbxEstado.setEnabled(false);
            txtTelefone.setEnabled(false);
            txtRG.setEnabled(false);
            txtCelular.setEnabled(false);
            txtEmail.setEnabled(false);
            txtFormacao.setEnabled(false);
            txtArea.setEnabled(false);
            btnConsultar.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnInserir.setEnabled(false);

            txtCPF.setText("");
            txtNome.setText("");
            txtData.setText("");
            cbxSexo.setToolTipText("M");
            cbxEstadoCivil.setToolTipText("Solteiro");
            txtEndereco.setText("");
            txtNumero.setText("");
            txtBairro.setText("");
            txtCEP.setText("");
            txtCidade.setText("");
            cbxEstado.setToolTipText("SP");
            txtCelular.setText("");
            txtRG.setText("");
            txtTelefone.setText("");
            txtEmail.setText("");
            txtFormacao.setText("");
            txtArea.setText("");
            txtCPF.requestFocus();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFormacao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JFormattedTextField txtRG;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
    Instrutor instrutor = null;
    DaoInstrutor daoInstrutor = null;
    Conexao conexao = null;
}
